import React, { useState } from 'react'
import {
  BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip,
  ResponsiveContainer,
} from 'recharts'
import { SectionTitle, MetricCard, Alert } from '../components/ui'

const FEATURE_CATEGORIES = [
  {
    category: 'Temporal Dynamics',
    description: 'Cyclical transformations and diurnal indicators to capture attack scheduling.',
    features: [
      { name: 'hour', type: 'Integer (0-23)', description: 'Hour of log request in UTC' },
      { name: 'minute', type: 'Integer (0-59)', description: 'Minute mark within the hour' },
      { name: 'day_of_week', type: 'Integer (0-6)', description: 'Day index (0=Monday, 6=Sunday)' },
      { name: 'is_weekend', type: 'Boolean (0/1)', description: '1 if Saturday or Sunday, else 0' },
      { name: 'hour_sin', type: 'Float (-1 to 1)', description: 'Sine cyclical encoding of hour: sin(2π·hour/24)' },
      { name: 'hour_cos', type: 'Float (-1 to 1)', description: 'Cosine cyclical encoding of hour: cos(2π·hour/24)' },
    ],
  },
  {
    category: 'IP & Host Behavior',
    description: 'Aggregations measuring request rates, concurrency, and port scanning indicators.',
    features: [
      { name: 'requests_per_ip', type: 'Integer', description: 'Cumulative requests generated by the client IP' },
      { name: 'requests_per_ip_hour', type: 'Integer', description: 'Request frequency within the active hour window' },
      { name: 'requests_per_ip_minute', type: 'Integer', description: 'Burst rate of requests within a single minute' },
      { name: 'unique_ports_per_ip', type: 'Integer', description: 'Distinct target port count (signals port scans)' },
      { name: 'unique_paths_per_ip', type: 'Integer', description: 'Distinct URIs accessed (signals directory fuzzers)' },
    ],
  },
  {
    category: 'Lexical & User-Agent Profiling',
    description: 'Entropy and string characteristics used by automated tools and custom bots.',
    features: [
      { name: 'user_agent_length', type: 'Integer', description: 'Total character length of User-Agent string' },
      { name: 'user_agent_entropy', type: 'Float', description: 'Shannon entropy measuring randomness of User-Agent' },
      { name: 'is_browser', type: 'Boolean (0/1)', description: 'Matches standard Chrome/Safari/Firefox regex' },
      { name: 'bot_indicator_none', type: 'Boolean (0/1)', description: 'Absence of known bot signatures' },
      { name: 'scanner_indicator_none', type: 'Boolean (0/1)', description: 'Absence of Gobuster/DirBuster/Nmap keywords' },
    ],
  },
  {
    category: 'Rapid-Fire & Interaction Anomalies',
    description: 'Heuristic thresholds identifying automated script executions and brute force attempts.',
    features: [
      { name: 'rapid_request', type: 'Boolean (0/1)', description: 'Successive request delta < 10 seconds' },
      { name: 'rapid_request_5s', type: 'Boolean (0/1)', description: 'Successive request delta < 5 seconds' },
      { name: 'rapid_request_1s', type: 'Boolean (0/1)', description: 'Successive request delta < 1 second (bot signature)' },
      { name: 'rapid_and_high_volume', type: 'Boolean (0/1)', description: 'Composite interaction: rapid_request AND >500 reqs' },
      { name: 'scanner_and_high_volume', type: 'Boolean (0/1)', description: 'Composite interaction: scanner flag AND >500 reqs' },
    ],
  },
]

const TOP_IMPORTANCE = [
  { feature: 'bot_indicator_none', importance: 0.0673, category: 'Lexical' },
  { feature: 'scanner_indicator_none', importance: 0.0450, category: 'Lexical' },
  { feature: 'requests_per_ip_hour', importance: 0.0447, category: 'Behavioral' },
  { feature: 'requests_per_ip_minute', importance: 0.0408, category: 'Behavioral' },
  { feature: 'user_agent_length', importance: 0.0395, category: 'Lexical' },
  { feature: 'scanner_and_high_volume', importance: 0.0375, category: 'Composite' },
  { feature: 'is_browser', importance: 0.0373, category: 'Lexical' },
  { feature: 'rapid_request', importance: 0.0360, category: 'Anomaly' },
  { feature: 'rapid_request_5s', importance: 0.0344, category: 'Anomaly' },
  { feature: 'user_agent_entropy', importance: 0.0340, category: 'Lexical' },
  { feature: 'requests_per_ip', importance: 0.0330, category: 'Behavioral' },
  { feature: 'rapid_request_1s', importance: 0.0261, category: 'Anomaly' },
]

export default function FeaturesPage() {
  const [selectedCategory, setSelectedCategory] = useState<string>('All')
  const [searchTerm, setSearchTerm] = useState<string>('')

  const allFeatures = FEATURE_CATEGORIES.flatMap((c) =>
    c.features.map((f) => ({ ...f, category: c.category }))
  )

  const filteredFeatures = allFeatures.filter((f) => {
    const matchCat = selectedCategory === 'All' || f.category === selectedCategory
    const matchSearch =
      f.name.toLowerCase().includes(searchTerm.toLowerCase()) ||
      f.description.toLowerCase().includes(searchTerm.toLowerCase())
    return matchCat && matchSearch
  })

  return (
    <div>
      <SectionTitle
        title="Feature Engineering Architecture"
        sub="Practical 05: Construction of 33+ multi-dimensional behavioral, temporal, and lexical signals"
      />

      {/* Metrics */}
      <div className="metric-grid">
        <MetricCard label="Engineered Features" value="33 Signals" sub="Extracted from raw logs" accent="orange" />
        <MetricCard label="Feature Matrix File" value="746 MB" sub="features.csv (51 columns)" accent="purple" />
        <MetricCard label="Top Signal (RF)" value="6.73%" sub="bot_indicator_none" accent="green" />
        <MetricCard label="Leakage Advisory" value="Flagged" sub="Practical 09 leakage analysis" accent="yellow" />
      </div>

      <div style={{ marginBottom: 20 }}>
        <Alert type="warning">
          <strong>Data Leakage Note (Practical 09 Finding):</strong> The features{' '}
          <code>bot_indicator_none</code> and <code>scanner_indicator_none</code> were derived from
          the labeling heuristic dictionary. While they achieve 99.21% accuracy in Random Forest evaluation,
          true production deployment relies heavily on behavioral features like{' '}
          <code>requests_per_ip_hour</code>, <code>user_agent_entropy</code>, and <code>rapid_request_1s</code>.
        </Alert>
      </div>

      {/* Top Feature Importance Chart */}
      <div className="chart-container" style={{ marginBottom: 24 }}>
        <div className="chart-title">Feature Importance Hierarchy (Random Forest Gini Impurity)</div>
        <ResponsiveContainer width="100%" height={340}>
          <BarChart data={TOP_IMPORTANCE} layout="vertical" margin={{ top: 5, right: 30, bottom: 5, left: 160 }}>
            <defs>
              <linearGradient id="featBarGrad" x1="0" y1="0" x2="1" y2="0">
                <stop offset="0%" stopColor="#FF6B00" />
                <stop offset="100%" stopColor="#FF9E4A" />
              </linearGradient>
            </defs>
            <CartesianGrid strokeDasharray="4 4" stroke="rgba(255,255,255,.04)" horizontal={false} />
            <XAxis
              type="number"
              tick={{ fill: '#64748B', fontSize: 10 }}
              tickFormatter={(v) => `${(v * 100).toFixed(1)}%`}
              tickLine={false}
              axisLine={{ stroke: 'rgba(255,255,255,0.08)' }}
            />
            <YAxis
              type="category"
              dataKey="feature"
              tick={{ fill: '#CBD5E1', fontSize: 11, fontFamily: 'var(--font-mono)' }}
              tickLine={false}
              axisLine={false}
            />
            <Tooltip
              content={({ active, payload, label }: any) => {
                if (!active || !payload?.length) return null
                return (
                  <div style={{
                    background: 'rgba(13, 19, 34, 0.95)',
                    backdropFilter: 'blur(12px)',
                    border: '1px solid rgba(255, 255, 255, 0.12)',
                    boxShadow: '0 12px 30px rgba(0,0,0,0.6)',
                    borderRadius: 8,
                    padding: '8px 12px',
                    fontSize: '.75rem',
                  }}>
                    <div style={{ color: '#94A3B8', marginBottom: 4, fontFamily: 'var(--font-mono)' }}>{label}</div>
                    <div style={{ color: '#FF9E4A', fontWeight: 700, fontFamily: 'var(--font-mono)' }}>
                      Importance: {(Number(payload[0].value) * 100).toFixed(2)}%
                    </div>
                  </div>
                )
              }}
            />
            <Bar dataKey="importance" fill="url(#featBarGrad)" radius={[0, 6, 6, 0]} />
          </BarChart>
        </ResponsiveContainer>
      </div>

      {/* Features Catalog */}
      <div className="chart-container">
        <div className="page-header" style={{ marginBottom: 16 }}>
          <div className="chart-title" style={{ margin: 0 }}>Feature Catalog & Specifications</div>
          <div style={{ display: 'flex', gap: 10 }}>
            <input
              type="text"
              placeholder="Search features..."
              className="input"
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              style={{ width: 220 }}
            />
            <select
              className="select"
              value={selectedCategory}
              onChange={(e) => setSelectedCategory(e.target.value)}
            >
              <option value="All">All Categories</option>
              {FEATURE_CATEGORIES.map((c) => (
                <option key={c.category} value={c.category}>
                  {c.category}
                </option>
              ))}
            </select>
          </div>
        </div>

        <div style={{ overflowX: 'auto' }}>
          <table className="data-table" style={{ width: '100%' }}>
            <thead>
              <tr>
                <th>Feature Name</th>
                <th>Category</th>
                <th>Data Type</th>
                <th>Description</th>
              </tr>
            </thead>
            <tbody>
              {filteredFeatures.map((f) => (
                <tr key={f.name}>
                  <td className="mono" style={{ color: 'var(--accent)', fontWeight: 600 }}>
                    {f.name}
                  </td>
                  <td>
                    <span className="badge" style={{ background: '#27272a' }}>
                      {f.category}
                    </span>
                  </td>
                  <td className="mono" style={{ fontSize: '.75rem', color: '#a1a1aa' }}>
                    {f.type}
                  </td>
                  <td style={{ fontSize: '.8rem' }}>{f.description}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  )
}
